spring:
  application:
    name: stm-db-init

  datasource:
    url: jdbc:postgresql://localhost:5432/stm_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        options: "-c TimeZone=Asia/Ho_Chi_Minh"

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true
    mixed: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org.flywaydb: DEBUG
